FROM python:3.12-slim

#Crear carptea de trabajo
WORKDIR /app

#Copia de los requerimientos
COPY requirements.txt .

#Instalación
RUN pip install --no-cache-dir -r requirements.txt

#Copiar el cóidgo del proyecto
COPY ./app ./app

#Exponer el puerto de trabajo
EXPOSE 8000

#Comandos para ejecutar FAST API
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]